- block:

  - name: Install Systemd unit files
    # The template allows us to specify the platform python environment.
    template:
      src: 'templates/{{ item }}.j2'
      dest: '/etc/systemd/system/{{ item }}.service'
    with_items:
      - pulp_resource_manager
      - pulp_worker@

  - name: Start or Restart tasking services
    systemd:
      daemon_reload: true
      enabled: true
      name: '{{ item }}'
      state: restarted
    with_items:
      - pulp_resource_manager
      - pulp_worker@1
      - pulp_worker@2

  become: true
