- name: Install Systemd unit files
  # The template allows us to specify the platform python environment.
  template:
      src: "templates/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
    - pulp_resource_manager
    - pulp_worker@
- name: Create /var/cache/pulp directory
  file:
    path: /var/cache/pulp
    state: directory
    owner: "{{ pulp_user }}"
    group: "{{ pulp_user }}"

- name: reload systemd units
  command: systemctl daemon-reload

- name: Start or Restart tasking services
  service:
      name: "{{ item }}"
      state: restarted
      enabled: true
  with_items:
      - pulp_worker@1
      - pulp_worker@2
      - pulp_resource_manager
