# These can go away when https://fedorahosted.org/spin-kickstarts/ticket/59 is fixed
- name: Grant vagrant all sudo rights
  lineinfile:
      create: yes
      dest: /etc/sudoers.d/vagrant-nopasswd
      regexp: '^vagrant'
      line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
      mode: 0440

- name: Ensure homedir mode suitable for calling processes in its virtualenvs
  file:
    dest: "{{ unprivileged_homedir }}"
    mode: 0755

- copy:
    src: motd
    dest: /etc/motd

- name: Ensure unprivileged user can read the systemd journal
  user:
      name: "{{ ansible_user }}"
      state: present
      groups: systemd-journal
      append: true
