---
# Install Pulp 3 from source.
#
# The resultant installation is designed to be useful for developers. It does
# things like install code in editable mode, install extra dependencies and
# install Bash aliases.
- hosts: all
  vars:
    pulp_user: vagrant
    use_rabbitmq: False
  pre_tasks:
    - name: Require Ansible 2.4+
      assert:
        that:
          - ansible_version.full|version_compare('2.4', operator='ge')
        msg: >
          This playbook requires Ansible 2.4+. Consider creating a virtualenv
          and installing Ansible with pip.
  roles:
    - pulp-user
    - db
    - broker
    - dev
    - {role: plugin, plugin_name: 'pulp_file', app_label: 'pulp_file'}
    # - {role: plugin, plugin_name: 'pulp_python', app_label: 'pulp_python'}
    - systemd
    - role: dev_tools
      when: ansible_distribution == 'Fedora'
