---
# Install Pulp 3 from source.
#
# The resultant installation is designed to be useful for developers. It does
# things like install code in editable mode, install extra dependencies and
# install Bash aliases.
- hosts: pulp3_dev
  become: true
  vars:
    pulp_user: vagrant
  pre_tasks:
    # Developers want to know if Pulp works with the latest packages.
    - name: Upgrade all currently installed packages
      package:
        name: '*'
        state: latest
  roles:
    - pulp-user
    - db
    - broker
    - lazy
    - dev
    - plugins
    - reset_db
    - systemd
    # - pulp_ca
    # - smash
    # - pulpproject
    - dev_tools
    # - release
    # - debug
