---
# Install Pulp 3 from source.
#
# The resultant installation is designed to be useful for developers. It does
# things like install code in editable mode, install extra dependencies and
# install Bash aliases.
- hosts: all
  vars:
    pulp_user: vagrant
  pre_tasks:
    - name: Require Ansible 2.4+
      assert:
        that:
          - ansible_version.full is version_compare('2.4', operator='ge')
        msg: >
          This playbook requires Ansible 2.4+. Consider creating a virtualenv
          and installing Ansible with pip.
  roles:
    - role: configure_rhel_7
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    - pulp-user
    - db
    - redis
    - dev
    - {role: plugin, plugin_name: 'pulp_file', app_label: 'pulp_file'}
    # - {role: plugin, plugin_name: 'pulp_python', app_label: 'pulp_python'}
    - django_db
    - systemd
    - role: dev_tools
      when: ansible_distribution == 'Fedora'
